### ISSUE TITLE
Would using a physics library reduce our development time ?

### ISSUE THREAD

**Issue by DirectuX** [petrSchreiber/BetweenTheBubbles-tb#24]
The Pilgrim is gliding on water with friction. Vectors for bump calculations will certainly be used... Echoes like a call for a physics library.

**Comment by petrSchreiber** [comment]
Thank you for the idea, Sebastian,

what I know is that using raw thinBASIC _may_ get us to performance issues with multiple objects.

The bump mechanics, dragging and more are not that complex, could be achieved with #compiled / #endcompiled and FreeBASIC JIT performance boost.

However,  if you know a good physics library, I am all for it. Usually, the trouble with 3rd party physics libraries comes once the use callbacks. Callbacks expect compiled function, which thinBASIC as interpreter cannot offer.

Could be again hacked in by using #compiled freebasic part :)

**Comment by petrSchreiber** [comment]
// I am currently going the way of ECS + simple physics system, so far so good, optimization needed, but ideas in mind

Why: Educational value

**Comment by DirectuX** [comment]
Considering later email conversations, I agree to not use third-party library for physics.
