### ISSUE TITLE
Procedural map - river stirring

### ISSUE THREAD

**Issue by DirectuX** [petrSchreiber/BetweenTheBubbles-tb#31]
Following up on Cornelius stress-test, and issue #29 

it is possible to define border limits for stirring, then apply different settings inside the limits for each world.

**Comment by petrSchreiber** [comment]
Hi Sebastian,

do I understand correctly, that for example now, the river generation is done in rectangle W x H:

(F = free, B = blocked)
```
X X X X X X
X . . . . X
X . . . . X
X . . . . X
X . . . . X
X X X X X X
```
...but you are considering adding further "natural blocks" where rivers would not be able to flow?:
```
X X X X X X
X . . X . X
X X . X . X
X X . . . X
X X . . . X
X X X X X X
```

Just checking I understand correctly, thank you!

**Comment by DirectuX** [comment]
not like that : 

currently limits are : 
- borders of the map (mapDimensions as tXY)
- the river meander 

There was (removed for debugging) random reduction of expansion of the river ( 15% - 85% ) (maxExpandPlace as dWord)

New proposition is _adding further "natural blocks" where rivers would not be able to flow_  

I'll make an infographic maybe this w-e; after I read all your answers.

**Comment by petrSchreiber** [comment]
Sure - an image would help me here a lot. Thank you 👍

**Comment by DirectuX** [comment]
I did not made a picture to explain previous and actual behaviour of Cornelius. They will be obsolete soon I hope. Basically, **first version** was buggy but size of meander and displacement of meander were random **over the whole map surface**.  **Second version** (for debugging) only the meander size was random. Displacement was automatically **set to the max** over the whole map surface.

**New proposition** : as first version + random is within **limits**.

For new proposition with respect of all talked constraints : See picture in #29

**Comment by petrSchreiber** [comment]
I like the concept of **limits**, let's follow this path! Closing this one?
