### ISSUE TITLE
Infinite bubbleVerse

### ISSUE THREAD

**Issue by DirectuX** [petrSchreiber/BetweenTheBubbles-tb#45]
**Is it still infinite ?** or does this implies the idea is dropped back to v1 ? (Both are Ok to me)

![btb4](https://user-images.githubusercontent.com/17156661/82130192-7ecff500-97c9-11ea-88bc-1e48ac611d74.jpg)

**Click the image to full resolution**

_Originally posted by @DirectuX in https://github.com/petrSchreiber/BetweenTheBubbles-tb/issues/29#issuecomment-629706192_

**Comment by petrSchreiber** [comment]
Infinite bubbleverse is tempting, but I think these generated sections are more fun and focused.

If I may:
- no infinite bubbleverse, just limited bubbleverse :)

**Comment by DirectuX** [comment]
> no infinite bubbleverse, just limited bubbleverse

ok :)
