### ISSUE TITLE
function makeElementsFlow() Question

### ISSUE THREAD

**Issue by DirectuX** [petrSchreiber/BetweenTheBubbles-tb#6]
Hi Petr, 

can you explain why this line code is bound to _me.player.energy_ ?

https://github.com/petrSchreiber/BetweenTheBubbles-tb/blob/2448a4ba78c7159cb3efa2a17ad43813004b6596/src/screen_definitions/game.tbasicu#L137

**Comment by petrSchreiber** [comment]
Hi Sebastian,

it was an experiment.

The idea was that more energy the bug has, the fastest it can flow on its own.

**Comment by DirectuX** [comment]
understood. Maybe we can link the flow with another variable. Variable we can adjust for the difficulty as the levels change. (To me) it seems not logic that the bug's environment can be influenced by the bug's energy. At least in this state of the BubbleVerse. Do you agree ?

**Comment by petrSchreiber** [comment]
I do agree, it was just an experiment 👍

**Comment by DirectuX** [comment]
Added to BTB.cts
